spring.application.name=demo
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/survey_db
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Email OTP configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=xhoang345@gmail.com
spring.mail.password=npod ltds txyt uyre
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT configuration
app.jwt.secret=${JWT_SECRET:DayLaMotChuoiBiMatRatDaiVaKhongTheBiLo123456}
app.jwt.expiration-ms=3600000
